### ISSUE TITLE
Thank you and reporting some minor issues

### ISSUE THREAD

**Issue by IgorIzyurov** [tinmarino/mouse_xterm#2]
Hi! Thank you for this awesome solution and for sharing it! Isn't it weird that so important and old tool like linux terminal stays so inconvenient in 2021? Its history stems from teletypes as physical devices, which didn't have cursor, obviously, but  it is not an excuse imho.

Anyway, thanks for your efforts. The code works well if sourcing mouse.sh within an already running session, but when I saved the lines in `.bashrc` and rebooted, I got a creepy message:

![image](https://user-images.githubusercontent.com/56837204/129964171-8d7549b8-00d5-4bac-ab7a-6b94ed053e84.png)

It doesn't seem to affect anything, but that's not something one would wish to see at startup...

Another issue: the terminal cursor lands 18 characters to the right of the mouse cursor.
On the screenshot the latter is not visible, but it is located exactly after `~$`

![image](https://user-images.githubusercontent.com/56837204/129965492-d83df363-baca-4331-8aaa-b184d25f3ea2.png)

**Comment by tinmarino** [comment]
Hi @IgorIzyurov,

For the init warning the "problem" is that you source your ~/.bashrc from your ~/.profile. So you must exit before the bind command with some typical `[[ -z "$PS1" ]] && return`.

I'll have a look at the arithmetic which is very few code actually. I am not surprise there is a bug but this make the script useless.

Concerning themouse, terminals are ok. It is the applications (here bash) that do not behave nicely. But Vim for instance has a perfect mouse support. 

Edit (sry I forgot to write): Thank you very much for the report / issue

**Comment by tinmarino** [comment]
Hi @IgorIzyurov, 

The PS1 should have fixe your warning.
For the arithmetic, maybe you `PS1` variable misses `\[` for invisible characters.

Please attach the output of
```
env  # BASH_VERSION, PS1, PROMPT_COMMAND
cat /tmp/xterm_monitor
```

So that I can repeat your offset

**Comment by tinmarino** [comment]
Ok, I still have "2" has the harcoded PS1 len, syr my bad. The 18 offset is the len of your PS1 minus 2.

It could  be retrieved movying cursor to the start (READLINE) and getting cursor position (CTLSEQ)

**Comment by tinmarino** [comment]
Fixed: I used to substract an hardcoded 2 for the length of the PS1 prompt, so you had the cursor (prompt_len -2) characters too far on the right.
