### ISSUE TITLE
Issue starting tracker

### ISSUE THREAD

**Issue by NotAlexNoyle** [tinmarino/mouse_xterm#3]
$ mouse_track_start
bash: 1mouse_track_echo_enable: ambiguous redirect
<halt>

**Comment by tinmarino** [comment]
Hello @NotAlexNoyle, thank you for reaising the issue and sorry for the late response.

I think this is due to your PROMPT_COMMAND which is not terminated with ";" . In that case, the referenced commit should have fixed it.

Otherwise, could you send me the output of
```
echo $PROMPT_COMMAND
cat /tmp/xterm_monitor
````
