### ISSUE TITLE
Syntax error: operand expected

### ISSUE THREAD

**Issue by isarandi** [tinmarino/mouse_xterm#4]
On Ubuntu 18.04 I get the following error within a Terminator terminal: 

```
bash:  y0=<0 : y0=<0 : syntax error: operand expected (error token is "<0 ")
```

**Comment by tinmarino** [comment]
Hi @isarandi, thank you for the report.
Can you please attach the output of

```
echo $PROMPT_COMMAND
cat /tmp/xterm_monitor
```

It seems that your mouse click are triggering mode `<`, or maybe those are not well eaten by the bind command.
I could just remove the extra `<` before affecting it to `y` but I'd like to know where it comes from.

Cheers.

**Comment by tinmarino** [comment]
It should have been fixed with some stringer types
